## Getting Started With [Tensorflow](https://www.tensorflow.org/guide)

`TensorFlow` is an end-to-end platform for machine learning. It supports the following:

- Multidimensional-array based numeric computation (similar to NumPy.)
- GPU and distributed processing
- Automatic differentiation
- Model construction, training, and export

### Install Tensorflow
```py
pip install tensorflow
```

In [1]:
#let us now cover the basics stuff of Tensorflow
#Before that let us understand what are Tensors

In [2]:
import tensorflow as tf

### Tensors

Just like in Numpy where we delt with multi-dimensional arrays. Tensorflow operates on tensors or multidimensional arrays.

In [5]:
tensor_ = tf.constant([[1,2,3],[4,5,6]])

In [6]:
type(tensor_)

tensorflow.python.framework.ops.EagerTensor

In [8]:
tensor_.shape

TensorShape([2, 3])

In [9]:
tensor_

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [10]:
single_arr = tf.constant([1,2,3],dtype="float")

In [11]:
single_arr

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

Tensors have shapes. Some vocabulary:

- Shape: The length (number of elements) of each of the axes of a tensor.
- Rank: Number of tensor axes. A scalar has rank 0, a vector has rank 1, a matrix is rank 2.
- Axis or Dimension: A particular dimension of a tensor.
- Size: The total number of items in the tensor, the product of the shape vector's elements.


In [13]:
tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]], dtype=int32)>

![3Dtensor](https://www.tensorflow.org/guide/images/tensor/3-axis_numpy.png "Representation Of 3D Tensor") 
![3D](https://www.tensorflow.org/guide/images/tensor/3-axis_front.png "3D Tensor")

### Common Operations

In [14]:
arr1 = tf.constant([1,2,3,4,5])
arr2 = tf.constant([10,11,12,14,13])

In [16]:
sum = tf.add(arr1,arr2)

In [17]:
sum.numpy()

array([11, 13, 15, 18, 18], dtype=int32)

In [19]:
diff = tf.subtract(arr1,arr2)

In [20]:
diff.numpy()

array([ -9,  -9,  -9, -10,  -8], dtype=int32)

In [21]:
mul = tf.multiply(arr1,arr2)

In [22]:
mul.numpy()

array([10, 22, 36, 56, 65], dtype=int32)

### Variable

A TensorFlow variable is the recommended way to represent shared, persistent state your program manipulates. This guide covers how to create, update, and manage instances of tf.Variable in TensorFlow.

In [23]:
arr = tf.Variable([1,2,3,4],dtype="float")

In [24]:
arr

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

In [25]:
type(arr)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

### Matrix Multiplication

In [28]:
a = tf.Variable([[2,3,4],
                [3,2,3],
                 [4,2,1]])  #3x3
b = tf.Variable([[1,2],
                [5,2],
                 [7,0]])  #3x2

In [30]:
mul = tf.matmul(a,b) #(3x3) x (3x2) = (3x2)

In [31]:
mul

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[45, 10],
       [34, 10],
       [21, 12]], dtype=int32)>

### Function In Tensorflow

In [46]:
def regression_formula(W,X,b):
  y_hat = tf.matmul(tf.transpose(W),X)
  y_hat = y_hat+b
  return y_hat

z = tf.function(regression_formula)

X = tf.constant([[1,2,3],[4,5,6],[7,8,9]],dtype="float")
W = tf.fill([3,1],0.1)
b = tf.Variable(0.0)

predict = z(W,X,b)

In [47]:
predict

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1.2      , 1.5      , 1.8000001]], dtype=float32)>

### Broadcasting

Broadcasting is a concept borrowed from the equivalent feature in NumPy. In short, under certain conditions, smaller tensors are "stretched" automatically to fit larger tensors when running combined operations on them.

In [49]:
tf.broadcast_to(tf.constant([1,2,3]), [3, 3])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]], dtype=int32)>

### Modules, Layers and Models

In [59]:
class FirstModule(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)
        self.trainable_var = tf.Variable(10.0, name="train")
        self.non_trainable_var = tf.Variable(10.0, trainable=False, name="train_me")
    def __call__(self, x):
        return x*(self.trainable_var * self.non_trainable_var)

module = FirstModule(name="tesnorflow_is_Awesome")
module(tf.constant(2.0))  #(2*(10*10))=200.0

<tf.Tensor: shape=(), dtype=float32, numpy=200.0>

A callable is anything that can be called.

The built-in callable (PyCallable_Check in objects.c) checks if the argument is either:
- an instance of a class with a __call__ method or
- is of a type that has a non null tp_call (c struct) member which indicates callability otherwise (such as in functions, methods etc.)


In [60]:
class Dense(tf.Module):
    def __init__(self, in_features, out_features, name=None):
        super().__init__(name=name)
        self.W = tf.Variable(tf.fill([in_features, out_features],0.1), name='W')
        self.b = tf.Variable(tf.zeros([out_features]), name='b')

    def __call__(self, x):
        y = tf.matmul(x, self.W) + self.b
        return tf.nn.sigmoid(y)

In [61]:
class Sequential(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)

        self.dense_layer1 = Dense(in_features=3, out_features=3)
        self.dense_layer2 = Dense(in_features=3, out_features=1)
        
    def __call__(self, x):
        x = self.dense_layer1(x)
        return self.dense_layer2(x)

In [62]:
model = Sequential(name="Sequential_Model")
model(tf.constant([[1.0,2.0,3.0],[3.0,2.0,3.0]]))

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.5482734],
       [0.5515641]], dtype=float32)>

This is it... in case you want to explore more then check: [Tensorflow Documentation](https://www.tensorflow.org/guide/)