# NUMPY

Python is used for multiple purposes, and at most of the time we might deal with complex mathematics formulas and equations. In order to save time in hard coding all those Mathematical equations Python provides Numpy module. Numpy stands for `Numerical Python Library`, and this is widely used in implementing Neural Networks and in those algorithms where complex mathematics is required. 

### Benefits of using Numpy:
- An array object of arbitrary homogeneous items.
- Fast mathematical operations over arrays.
- Linear Algebra, Fourier Transforms, Random Number Generation.
- Vectorization and Broadcasting which helps to get rid of explicit for loop.

### Install Numpy
```py
pip install numpy
```
Now open interactive shell and check if numpy is installed or not.

```py
>>> import numpy
>>> numpy.__version__
'1.19.2'
```

If you get no error, then numpy is successfully installed. If you get ModuleNotFoundError then it means that numpy was not installed. 

In [1]:
import numpy as np

### Generating Array Using Numpy

In [2]:
arr_ran = np.arange(0,10,1)
arr_ran

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
type(arr_ran)

numpy.ndarray

### Size Of An Array

Size attribute is used to display the total length of the Numpy array. Don’t confuse it with length, eventhough they both does the same task the results are different, here is the proof. 

In [4]:
arr = np.array(range(1,10))
print("Length:",len(arr))
print("Size:",arr.size)

Length: 9
Size: 9


That is really weird, I did say prints different result, but here we are getting same result.

In [5]:
arr = np.array([range(1,10)])
print("Length:",len(arr))
print("Size:",arr.size)

Length: 1
Size: 9


What just happened here? Here we are dealing with dimensions. When we have single dimensional array, i.e., example-1. In example 1, the array was in single dimension and thus both len() and size executed the same result. But in example 2, the main hero is 2 dimension array, and len() executes 1, because it is used to deal with just 1D Array. And size is used to deal with multiple dimension. And that is the reason why we use size attribute to execute the total elements in the given array. 

### Memory Bytes Of An Array

`itemsize` gives the memory size of one element of NumPy array in bytes.

In [6]:
arr = np.arange(10)
arr.size*arr.itemsize

80

In [7]:
#Method 2

`nbytes` calculates the total bytes used by the elements of the NumPy array.

In [8]:
arr.nbytes

80

### N-Dimensional Arrays

N-Dimensional Arrays means Multiple Dimensional Arrays. Where N is integer value starts from 2 and ends to N(infinity value). 

In [9]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr_2d.ndim

2

In [11]:
arr_2d.size

8

To check the dimension of the numpy array we use `ndim` attribute. 

### Shape And Reshape An Array

On introducing to N-dimensional array, we have come across to only size and dimension of the array. But in what matrix order is it in? The word Matrix is nothing but the collection of elements arranged in rows and columns. Furthermore, this Matrix is off different types: `Unit Matrix(np.ones)`, `Zero Matrix(np.zeros)`, `Square Matrix`, `Identity Matrix` and many more. All matrix are different but order. An order is usually written as (row x column), to be more precise `(mxn)`. Where m is the total number of rows and n is the total number of columns. 

Shape returns in Tuple i.e., (m,n) for two dimensional array, (m,n,o) for three dimensional array.  
m,n,o all are numeric value. For example: (1,2,3) or (1,2) or (2,)

In [12]:
n_arr = np.random.rand(10)
#we shall look into random array soon

In [13]:
n_arr

array([0.90670104, 0.86812133, 0.30734403, 0.866548  , 0.30626658,
       0.34626267, 0.08678111, 0.08647553, 0.15793107, 0.27290629])

In [14]:
n_arr.shape   #shape: returns in tuple
(10,)

(10,)

In [15]:
n_arr.ndim

1

Now lets reshape this array

In [16]:
n_arr = n_arr.reshape(2,5)

In [17]:
n_arr

array([[0.90670104, 0.86812133, 0.30734403, 0.866548  , 0.30626658],
       [0.34626267, 0.08678111, 0.08647553, 0.15793107, 0.27290629]])

In [18]:
n_arr.shape

(2, 5)

In [19]:
n_arr.ndim

2

As you can notice we now have a two dimension array instead of 1D array

**Note**: Always remember, since shape returns in tuple len(arr.shape) == arr.ndim. 
The length of the shape denotes the dimension of the given array. Thus len(arr.shape)== arr.ndim will return true. 

In [20]:
len(n_arr.shape)

2

In [21]:
len(n_arr.shape) == n_arr.ndim

True

#### this is how three dimensional array looks like. 

In [22]:
arr_3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [23]:
arr_3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [24]:
arr_3d.ndim

3

In [25]:
arr_3d.shape

(1, 3, 3)

### How to create a Random Array?

Creating an array filled with random numbers is the most essential operation in Numpy. Sometimes when you need large size of data with bigger dimensions we commonly prefer the array with random values.

In [26]:
arr10 = np.random.random(10)
print(arr10)

[0.2562984  0.15938578 0.15049675 0.63324645 0.86147627 0.84687902
 0.72028901 0.79851544 0.51891435 0.39289342]


In [27]:
#second method

In [28]:
arr10 = np.random.rand(10)

In [29]:
arr10

array([0.36131531, 0.15989942, 0.36895306, 0.26205127, 0.97809045,
       0.86398779, 0.26332666, 0.37480093, 0.67591729, 0.19216413])

In [30]:
arr_with_nega = np.random.randn(5)
arr_with_nega

array([-0.05931794,  0.57123765,  0.7562192 , -0.00154369, -0.58999977])

### Difference Between random.rand() vs random.random()

In [31]:
random_25_arr = np.random.random(25,3)

TypeError: random() takes at most 1 positional argument (2 given)

In [ ]:
random_25_arr = np.random.rand(25,3)

In [ ]:
random_25_arr

np.random.random is used to return random numbers of only 1D array whereas np.random.rand works on any dimension

### Indexing And Slicing Of Numpy Array

Indexing is the method to find the element at the specific location i.e., index

In [32]:
work_on_index = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [33]:
work_on_index

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
work_on_index.shape #3 rows and 4 columns

(3, 4)

In [35]:
work_on_index[0][0]  #returns the first index from the first row

1

In [36]:
work_on_index[0]  #returns first row

array([1, 2, 3, 4])

In [37]:
work_on_index[-1]

array([ 9, 10, 11, 12])

Slicing is the method that is used to select the specific sequence of elements from the array

```py
Syntax to slice: array[row_start:row_end,column_start:column_end]
```

In [38]:
work_on_slice = work_on_index

In [39]:
work_on_slice

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
work_on_slice[0:2]  #to select first 2 rows

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [44]:
work_on_slice[1:2,0:2]  #2nd row[5,6,7,8] and 0 to 1 column[5,6]

array([[5, 6]])

In [48]:
work_on_slice[[0,-1]]  #first and last row

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [56]:
work_on_slice[0:,-1]  #last column

array([ 4,  8, 12])

Using step size i.e., the third slice index:
    
```py
Syntax to slice_range: array[row_start:row_end:row_step,column_start:column_end:column_step]
```

In [59]:
work_on_slice[0::2,-1:]  #check the last column and select alternative postion

array([[ 4],
       [12]])

In [60]:
work_on_slice[0:3:2,0:-1:2]

array([[ 1,  3],
       [ 9, 11]])

In [61]:
work_on_slice

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Transpose Of The Array

Transpose of the matrix is the interchange of row and column elements. Transpose of the matrix also effects the shape of an array. For instance if the original array as 3 rows and 2 columns then the transpose of the matrix will have 2 rows and 3 columns. 

```py
Syntax: arr.T
```

In [ ]:
two_dim_arr = np.array([[10,20,30,40],[50,60,70,80]])
two_dim_arr

In [ ]:
two_dim_arr.shape

In [ ]:
two_dim_arr.T

In [ ]:
two_dim_arr.T.shape

The matrix order of original array is (2,4), as per the definition of Transpose Matrix, the transpose shape will be (4,2). 

### Mean, Media, Variance and Standard Deviation

Mean, Median, Variance and Standard Deviation, these concepts are considered to be types of Descriptive Statistics. Statistics? Yes it brings back the school days. There are two types of descriptive statistics, measures of central tendency and measures of spread. The mean, median and mode are all measures of central tendency, while the variance and standard deviation are measures of spread. Let us look into individual definitions.

In [ ]:
marks = [65,78,94,66,88,80,91]
marks = np.array(marks)
marks

### Mean

Mean is used to calculate the arithmetic average of the given data. It would only be used on quantitative data.

In [ ]:
mean = np.mean(marks)
print(mean)

In [ ]:
alternative_mean = sum(marks)/len(marks)
print(alternative_mean)

### Median

The median is the middle number in a sorted, ascending or descending, list of numbers and can be more descriptive of that data set than the average.

In [ ]:
median = np.median(marks)
print(median)

In [ ]:
marks.sort()
alternative_median = marks[len(marks)//2]
print(alternative_median)

### Variance

Variance is the sum of squares of differences between all numbers and means. It also defined as the average of the squares of the differences between the individual (observed) and the expected value.

In [ ]:
variance = np.var(marks)
print(variance)

In [ ]:
sum = 0
for i in marks:
    sum += (i-marks.sum()/len(marks))**2

alternative_variance = sum/len(marks)
print("%.4f"%alternative_variance)

### Standard Deviation

It is a measure of the extent to which data varies from the mean.

In [ ]:
std_deviation = np.std(marks)
print(std_deviation)

In [ ]:
alternative_std = np.sqrt(alternative_variance)
print("%.4f"%alternative_std)

### What Is Linspace?

Linspace divides a sequence evenly between start and end based on the step value. 

In [ ]:
distibution = np.linspace(0,100,5)
distibution

In [ ]:
distibution = np.linspace(0,100,2)
distibution

```
Note: We shall look at Vectorization and Broadcasting using Numpy while discussing Neural Network. But before we reach their, here are 3 important NumPy method to be familiarize with: 
1. Sum of Numpy Array
2. Matrix Multiplication or Dot Product
3. Exponential and Logarithms
```

### Sum of Array: Both Vertical and Horizontal

In [62]:
sum_arr_eg = np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4]])

In [63]:
sum_arr_eg

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [65]:
sum_arr_eg.sum()  #calculates the entire sum

30

In [66]:
sum_arr_eg.sum(axis=0) #0 goes downwards 

array([10, 10, 10])

In [67]:
sum_arr_eg.sum(axis=1) #1 goes sidewards

array([ 3,  6,  9, 12])

### Matrix Multiplication And Dot Product

In [82]:
w = np.random.rand(2,3) #mxn = 2x3
x = np.random.rand(3,1) #mxn = 3x1
#matrix mul = 2x3,3x1 = 2,1
#lets see the dimension

In [83]:
w

array([[0.83371804, 0.37163216, 0.96408014],
       [0.49731423, 0.33824397, 0.0631714 ]])

In [84]:
x

array([[0.62378394],
       [0.02285389],
       [0.33174581]])

In [85]:
matrix_mul = np.matmul(w,x)

In [86]:
matrix_mul

array([[0.84838271],
       [0.33890367]])

In [87]:
matrix_mul.shape

(2, 1)

In [88]:
dot_product = np.dot(w,x)

In [89]:
dot_product

array([[0.84838271],
       [0.33890367]])

### Exponential And Logarithms

In [74]:
np.exp(2)

7.38905609893065

In [75]:
y = 1.4
m = 3
c = 0.4
z = y*m + c
sigmoid = 1/(1+np.exp(-z))
sigmoid

0.9900481981330957

In [76]:
#we shall look into Sigmoid while discussing Logistic Regression

In [77]:
np.log(10)

2.302585092994046

In [78]:
np.log2(10)

3.321928094887362

In [79]:
np.log2(2)

1.0

In [80]:
np.log10(10)

1.0